# Generated by Django 5.1.7 on 2025-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_extra_data_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('drag_and_drop', 'Drag and Drop'), ('true_false', 'True/False')], default='multiple_choice', max_length=20),
        ),
    ]
